services:
  badge-leaderboard:
    build: ./
    env_file: ".env"
    restart: unless-stopped
    networks:
      - proxied
    environment:
      - FLASK_ENV=production
    volumes:
      - type: bind
        source: badges.jsonl
        target: /app/src/badges.jsonl
    labels:
      caddy: badges.areazerotcg.com
      caddy.reverse_proxy: "{{ upstreams 8000 }}"
